CREATE TABLE TEST (
id INTEGER PRIMARY KEY,
name VARCHAR(230)
);
--
--CREATE TABLE NEW_EMPLOYEE(
--   id INTEGER AUTO_INCREMENT PRIMARY KEY,
--   name VARCHAR(255) NOT NULL,
--   salary DOUBLE,
--   address VARCHAR(255)
--);
--
----DROP TABLE EMPLOYEE;